stages:
  - build

debian_stable:
  image: debian:stable
  before_script: &debian
    - apt-get -y update
    - apt-get -y upgrade
    - apt-get -y install cmake g++ perl
  stage: build
  script: &scr
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest
    - cat Testing/Temporary/LastTest.log

debian_testing:
  image: debian:testing
  before_script: *debian
  stage: build
  script: *scr

debian_sid:
  image: debian:testing
  before_script: *debian
  stage: build
  script: *scr

suse_current:
  image: opensuse/tumbleweed
  # rolling release with infinite life time
  before_script:
    - zypper -n patch || echo "do it again"
    - zypper -n patch
    - zypper -n ref
    - zypper -n up
    - zypper -n dup
    - zypper -n in cmake gcc-c++ perl
  stage: build
  script: *scr

# suse_stable:
#  opensuse:leap, unsupported here because it is at cmake 3.5, while libcerf requires 3.6

centos7:
  image: centos:centos7
  before_script:
    - yum -y update
    - yum -y install epel-release
    - yum repolist
    - yum -y install make cmake3 gcc-c++ perl
    - cmake3 --version
    - ctest3 --version
    - cpack3 --version
    - ln -s /usr/bin/cmake3 /usr/bin/cmake
    - ln -s /usr/bin/ctest3 /usr/bin/ctest
    - ln -s /usr/bin/cpack3 /usr/bin/cpack
  stage: build
  script: *scr
